import z from "zod";

export const autoGeneratedConferenceFormSchema = z.object({
    title: z.string().min(6, "Judul minimal 6 karakter"),
    description: z.string().optional(),
    dateFormat: z.string().min(1, "Format tanggal wajib diisi")
});

export type AutoGeneratedConferenceFormSchema = z.infer<typeof autoGeneratedConferenceFormSchema>