import { slugField } from "@/fields/slug";
import { CollectionConfig } from "payload";

const AutoGeneratedConferences: CollectionConfig = {
  slug: 'auto-generated-conferences',
  admin: {
    useAsTitle: 'title',
    group: 'Conferences',
  },
  access: {
    read: ({ req }) => !!req.user,
    create: ({ req }) => !!req.user,
    update: ({ req }) => !!req.user,
    delete: ({ req }) => !!req.user,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    {
      name: 'description',
      type: 'textarea',
      required: false,
    },
    ...slugField(),
    {
      name: 'dateFormat',
      type: 'text',
      required: true,
      admin: {
        description: 'Date in string format'
      }
    },
    {
      name : 'user',
      type : 'relationship',
      relationTo : 'users',
      hidden : false,
    
    }
  ],
  hooks : {
    
  }
};

export default AutoGeneratedConferences;