'use client';
import React from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useState } from "react";

import { autoGeneratedConferenceFormSchema, AutoGeneratedConferenceFormSchema } from "../type";
import { createAutoGeneratedConferenceAction } from "../actions";
import { useRouter } from "next/navigation";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";

export const AutoGeneratedConferenceForm: React.FC = () => {
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [submitError, setSubmitError] = useState<string | null>(null);
    const router = useRouter();
    const form = useForm<AutoGeneratedConferenceFormSchema>({
        resolver: zodResolver(autoGeneratedConferenceFormSchema),
        defaultValues: {
            title: "",
            description: "",
            dateFormat: ""
        }
    });

    const {
        reset
    } = form;

    const onSubmit = async (data: AutoGeneratedConferenceFormSchema) => {
        setIsSubmitting(true);
        setSubmitError(null);
        try {
            await createAutoGeneratedConferenceAction(data);
            window.location.href = "/dashboard/auto-conferences"
        } catch (error) {
            console.error("Pembuatan konferensi otomatis gagal:", error);
            setSubmitError(error instanceof Error ? error.message : "Terjadi kesalahan saat membuat konferensi");
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="min-h-screen bg-white p-4">
            <div className="w-full">
                {/* Header */}
                <div className="text-center mb-8">
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">Buat Konferensi Otomatis</h1>
                    <p className="text-gray-600">Tambahkan konferensi otomatis baru</p>
                </div>

                {/* Error Message */}
                {submitError && (
                    <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
                        <p className="text-red-700 text-sm">{submitError}</p>
                    </div>
                )}

                {/* Form */}
                <div className="space-y-6">
                    <Form  {...form}>
                        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                            <FormField
                                control={form.control}
                                name='title'
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Judul Konferensi</FormLabel>
                                        <FormControl>
                                            <Input
                                                type='text'
                                                placeholder='Masukkan judul konferensi'
                                                disabled={isSubmitting}
                                                {...field}
                                            />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            <FormField
                                control={form.control}
                                name='description'
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Deskripsi
                                            <span className="text-gray-500 text-xs ml-1">(opsional)</span>
                                        </FormLabel>
                                        <FormControl>
                                            <textarea
                                                rows={4}
                                                className="text-black flex w-full rounded-lg border px-4 py-3 text-base transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50 placeholder:text-gray-400 touch-manipulation border-gray-300 hover:border-gray-400"
                                                placeholder="Masukkan deskripsi konferensi (opsional)"
                                                disabled={isSubmitting}
                                                style={{
                                                    WebkitTapHighlightColor: 'transparent',
                                                    touchAction: 'manipulation'
                                                }}
                                                {...field}
                                            />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            <FormField
                                control={form.control}
                                name='dateFormat'
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Format Tanggal</FormLabel>
                                        <FormControl>
                                            <Input
                                                type='text'
                                                placeholder='Contoh: 25-12-2024 atau 12-2024'
                                                disabled={isSubmitting}
                                                {...field}
                                            />
                                        </FormControl>
                                        <FormMessage />
                                        <p className="text-sm text-gray-600 mt-1">
                                            Gunakan format DD-MM-YYYY (contoh: 25-12-2024) atau MM-YYYY (contoh: 12-2024)
                                        </p>
                                    </FormItem>
                                )}
                            />

                            {/* Submit Button */}
                            <Button
                                type="submit"
                                disabled={isSubmitting}
                                variant="default"
                                size="default"
                            >
                                {isSubmitting ? "Membuat Konferensi..." : "Buat Konferensi Otomatis"}
                            </Button>
                        </form>
                    </Form>
                </div>
            </div>
        </div>
    );
};

export default AutoGeneratedConferenceForm;