'use client';
import { AutoGeneratedConference } from "@/payload-types";
import { Share2, Trash2, ExternalLink, Copy } from "lucide-react";
import { PaginatedDocs } from "payload";
import { useState } from "react";
import { deleteAutoGeneratedConferenceById } from "../actions";
import { useRouter } from "next/navigation";

export default function ListAutoGeneratedConferences({
    docs
}: {
    docs: PaginatedDocs<AutoGeneratedConference>
}) {
    const [isDeleting, setIsDeleting] = useState<number | null>(null);
    const router = useRouter();
    
    const handleDelete = async (id: number) => {
        if (confirm("Apakah Anda yakin ingin menghapus konferensi otomatis ini?")) {
            setIsDeleting(id);
            try {
                await deleteAutoGeneratedConferenceById(id);
                router.refresh();
            } catch (error) {
                console.error("Gagal menghapus konferensi:", error);
            } finally {
                setIsDeleting(null);
            }
        }
    };

    async function handleCopy(conference: AutoGeneratedConference, type: 'audience' | 'user') {
        const url = type === 'audience' 
            ? `${window.location.origin}/${conference.slug || ''}` 
            : `${window.location.origin}/show/${conference.slug || ''}`;
        
        navigator.clipboard.writeText(url);
        alert(`Link ${type === 'audience' ? 'untuk peserta' : 'untuk melihat pertanyaan'} berhasil disalin ke clipboard!`);
    }

    const handleShare = (conference: AutoGeneratedConference, type: 'audience' | 'user') => {
        const url = type === 'audience' 
            ? `${window.location.origin}/${conference.slug || ''}` 
            : `${window.location.origin}/show/${conference.slug || ''}`;
        
        if (navigator.share) {
            navigator.share({
                title: conference.title,
                url: url,
            });
        } else {
            navigator.clipboard.writeText(url);
            alert(`Link ${type === 'audience' ? 'untuk peserta' : 'untuk melihat pertanyaan'} berhasil disalin ke clipboard!`);
        }
    };

    return <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {
            docs.docs.map((conference) => {
                return (
                    <div 
                        key={conference.id} 
                        className="bg-white rounded-lg shadow-md border border-gray-200 p-6 hover:shadow-lg hover:scale-105 transition-all duration-200 group"
                    >
                        <div className="flex justify-between items-start mb-4">
                            <h2 className="text-xl font-semibold text-gray-900 group-hover:text-gray-700">
                                {conference.title}
                            </h2>
                            <div className="flex gap-2 transition-opacity duration-200 z-10">
                                <button
                                    onClick={(e) => {
                                        e.preventDefault()
                                        e.stopPropagation()
                                        handleDelete(conference.id)
                                    }}
                                    disabled={isDeleting === conference.id}
                                    className="p-2 text-gray-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors duration-200 disabled:opacity-50"
                                    title="Hapus konferensi"
                                >
                                    {isDeleting === conference.id ? (
                                        <div className="w-4 h-4 animate-spin border-2 border-red-600 border-t-transparent rounded-full"></div>
                                    ) : (
                                        <Trash2 className="w-4 h-4" />
                                    )}
                                </button>
                            </div>
                        </div>
                        

                        <div className="space-y-2">
                            {/* Share for audience */}
                            <div className="flex items-center gap-2">
                                <button
                                    onClick={() => handleShare(conference, 'audience')}
                                    className="flex items-center gap-2 px-3 py-2 text-sm bg-blue-50 text-blue-700 hover:bg-blue-100 rounded-lg transition-colors duration-200"
                                    title="Bagikan untuk peserta"
                                >
                                    <Share2 className="w-4 h-4" />
                                    Bagikan untuk Peserta
                                </button>
                                <button
                                    onClick={() => handleCopy(conference, 'audience')}
                                    className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors duration-200"
                                    title="Salin link untuk peserta"
                                >
                                    <Copy className="w-4 h-4" />
                                </button>
                            </div>

                            {/* Share for user to view questions */}
                            <div className="flex items-center gap-2">
                                <button
                                    onClick={() => handleShare(conference, 'user')}
                                    className="flex items-center gap-2 px-3 py-2 text-sm bg-green-50 text-green-700 hover:bg-green-100 rounded-lg transition-colors duration-200"
                                    title="Bagikan untuk melihat pertanyaan"
                                >
                                    <ExternalLink className="w-4 h-4" />
                                    Lihat Pertanyaan
                                </button>
                                <button
                                    onClick={() => handleCopy(conference, 'user')}
                                    className="p-2 text-green-600 hover:bg-green-50 rounded-lg transition-colors duration-200"
                                    title="Salin link untuk melihat pertanyaan"
                                >
                                    <Copy className="w-4 h-4" />
                                </button>
                            </div>
                        </div>

                        <div className="mt-4 pt-4 border-t border-gray-100">
                            <div className="text-xs text-gray-400">
                                {conference.createdAt ? new Date(conference.createdAt).toLocaleDateString() : ''}
                            </div>
                        </div>
                    </div>
                );
            })
        }
    </div>
}