'use server';

import { getPayload } from "payload";
import { AutoGeneratedConferenceFormSchema } from "../type";
import config from "@payload-config";
import { QueryAction } from "@/types/query-action";
import { getMeUser } from "@/utilities/getMeUser";
// import { getMeUserServer } from "@/utilities/getMeUserServer";

export const findByIdAutoGeneratedConferences = async (slug: string) => {
    const payload = await getPayload({ config });

    const user = await getMeUser();

    const conferenceResult = await payload.find({
        collection: 'auto-generated-conferences',
        where: {
            and: [
                {
                    slug: {
                        equals: slug
                    }
                },
            ]
        },
        limit: 1
    });

    if (conferenceResult.docs.length === 0) {
        return null;
    }

    const conference = conferenceResult.docs[0];

    const questionsResult = await payload.find({
        collection: 'questions',
        where: {
            autoGeneratedConference: {
                equals: conference.id
            }
        },
        sort: 'createdAt',
        limit: 1000
    });

    return {
        conference,
        questions: questionsResult.docs
    };
}

export const findAllAutoGeneratedConferences = async () => {
    const payload = await getPayload({ config });
    const user = await getMeUser();
    if(!user.user) {
        return ;
    }
    return payload.find({
        collection: "auto-generated-conferences",
        where: {
            user: {
                equals: user?.user.id
            }
        }
    });
}

export const getAutoGeneratedConferences = async (queryAction: QueryAction) => {
    const payload = await getPayload({ config });
    const user = await getMeUser();
    if(!user.user) {
        return;
    }

    const limit = 10;
    const page = queryAction.page || 1;

    // Build the where clause
    const whereConditions: any[] = [
        {
            user: {
                equals: user.user.id
            }
        }
    ];

    // Add keyword search if provided
    if (queryAction.keyword && queryAction.keyword.trim() !== '') {
        whereConditions.push({
            or: [
                {
                    title: {
                        contains: queryAction.keyword
                    }
                },
                {
                    description: {
                        contains: queryAction.keyword
                    }
                }
            ]
        });
    }

    return payload.find({
        collection: "auto-generated-conferences",
        where: {
            and: whereConditions
        },
        limit,
        page,
        sort: '-createdAt'
    });
}

export const deleteAutoGeneratedConference = async (slug: string) => {
    const payload = await getPayload({ config });

    const deleted = await payload.delete({
        collection: "auto-generated-conferences",
        where: {
            slug: {
                equals: slug
            }
        }
    })

    return deleted;
}

export const deleteAutoGeneratedConferenceById = async (id: number) => {
    const payload = await getPayload({ config });

    try {
        
        const deleted = await payload.delete({
            collection: "auto-generated-conferences",
            id: id
        });

        return deleted;
    } catch (error) {
        console.error("Kesalahan menghapus konferensi:", error);
        throw new Error(`Gagal menghapus konferensi: ${error instanceof Error ? error.message : 'Kesalahan tidak diketahui'}`);
    }
}

export const createAutoGeneratedConferenceAction = async (conferenceForm: AutoGeneratedConferenceFormSchema) => {
    const payload = await getPayload({ config });

    const user = await getMeUser();

    if (user.user) {
        const slug = conferenceForm.title.toLowerCase().replace(/\s+/g, '-');

        // Check if slug already exists
        const existingConference = await payload.find({
            collection: "auto-generated-conferences",
            where: {
                slug: {
                    equals: slug
                }
            },
            limit: 1
        });

        if (existingConference.docs.length > 0) {
            throw new Error(`Slug "${slug}" sudah digunakan. Silakan gunakan judul yang berbeda.`);
        }

        const conference = await payload.create({
            collection: "auto-generated-conferences",
            data: {
                slug: slug,
                title: conferenceForm.title,
                description: conferenceForm.description || "",
                dateFormat: conferenceForm.dateFormat,
                user: user.user,
            },
            user: user.user,
        });

        return conference;
    }
}