"use client"

import { ColumnDef } from "@tanstack/react-table"
import { Question } from "@/payload-types"
import { SortableHeader } from "@/components/ui/data-table"
import Link from "next/link"
import { QuestionActions } from "./question-actions"

export const columns: ColumnDef<Question>[] = [
  {
    accessorKey: "question",
    header: ({ column }) => (
      <SortableHeader column={column}>Question</SortableHeader>
    ),
    cell: ({ row }) => {
      const question = row.getValue("question") as string
      return (
        <div className="max-w-[400px] font-medium">
          <div className="truncate" title={question}>
            {question}
          </div>
        </div>
      )
    },
  },
  {
    accessorKey: "name",
    header: ({ column }) => (
      <SortableHeader column={column}>Asked By</SortableHeader>
    ),
    cell: ({ row }) => {
      const name = row.getValue("name") as string
      return (
        <div className="font-medium">
          {name}
        </div>
      )
    },
  },
  {
    id: "conference",
    header: "Conference",
    cell: ({ row }) => {
      const question = row.original
      
      if (question.conference && typeof question.conference === 'object') {
        return (
          <Link 
            href={`/conferences/${question.conference.slug}`}
            className="hover:underline text-blue-600"
          >
            {question.conference.title}
          </Link>
        )
      }
      
      if (question.autoGeneratedConference && typeof question.autoGeneratedConference === 'object') {
        return (
          <Link 
            href={`/auto-conferences/${question.autoGeneratedConference.slug}`}
            className="hover:underline text-green-600"
          >
            {question.autoGeneratedConference.title} (Auto)
          </Link>
        )
      }
      
      return <span className="text-muted-foreground">No conference</span>
    },
  },
  {
    id: "conferenceType",
    header: "Type",
    cell: ({ row }) => {
      const question = row.original
      
      if (question.conference) {
        return (
          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
            Manual
          </span>
        )
      }
      
      if (question.autoGeneratedConference) {
        return (
          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
            Auto
          </span>
        )
      }
      
      return (
        <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
          Unknown
        </span>
      )
    },
  },
  {
    accessorKey: "createdAt",
    header: ({ column }) => (
      <SortableHeader column={column}>Created At</SortableHeader>
    ),
    cell: ({ row }) => {
      const date = row.getValue("createdAt") as string
      return (
        <div className="text-sm text-muted-foreground">
          {new Date(date).toLocaleDateString()}
        </div>
      )
    },
  },
  {
    id: "actions",
    cell: ({ row }) => {
      const question = row.original
      return <QuestionActions question={question} />
    },
  },
]