// storage-adapter-import-placeholder
import { postgresAdapter } from '@payloadcms/db-postgres'
import { payloadCloudPlugin } from '@payloadcms/payload-cloud'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import path from 'path'
import { buildConfig } from 'payload'
import { fileURLToPath } from 'url'
import sharp from 'sharp'

import { Users } from './collections/Users/config'
import { Posts } from './collections/Posts/config'
import { Categories } from './collections/Categories/config'
import { Media } from './collections/Media'
import getCloudStoragePlugin from './plugins/cloud-storage-plugin'
import Questions from './collections/Questions'
import Conferences from './collections/Conferences'
import AutoGeneratedConferences from './collections/AutoGeneratedConferences'
import { Accounts } from './collections/Account'
import getAuthPlugin from './plugins/auth-plugin'
import { getServerSideURL } from './utilities/getURL'
import { importExportPlugin } from '@payloadcms/plugin-import-export'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

export default buildConfig({
  serverURL: getServerSideURL(),
  admin: {
    user: Users.slug,
    importMap: {
      baseDir: path.resolve(dirname),
    },
  },
  collections: [Users,
     Posts, Categories,
    
    Media, Questions, Conferences, AutoGeneratedConferences, Accounts],
  editor: lexicalEditor(),
  secret: process.env.PAYLOAD_SECRET || '',
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: postgresAdapter({
    migrationDir :path.resolve(dirname, 'migrations'),
    pool: {
      connectionString: process.env.DATABASE_URI || '',
    },
  }),
  sharp,
  plugins: [
    payloadCloudPlugin(),
    getAuthPlugin(),
    // importExportPlugin({
    //   collections: ['questions', 'auto-generated-conferences', 'users', 'conferences', 'accounts'],
    //   // see below for a list of available options
    // }),
    // getCloudStoragePlugin(),
    // storage-adapter-placeholder
  ],
})
