"use client"

import { AutoGeneratedConference } from "@/payload-types"
import { ActionMenu } from "@/components/ui/data-table"
import { DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Edit, Trash2, Eye, Copy, Share2 } from "lucide-react"
import { useState } from "react"
import { deleteAutoGeneratedConferenceById } from "../../actions"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { useQueryClient } from "@tanstack/react-query"

interface AutoConferenceActionsProps {
  conference: AutoGeneratedConference
}

export function AutoConferenceActions({ conference }: AutoConferenceActionsProps) {
  const [isDeleting, setIsDeleting] = useState(false)
  const router = useRouter()
  const queryClient = useQueryClient()

  const handleDelete = async () => {
    if (confirm("Are you sure you want to delete this auto-generated conference?")) {
      setIsDeleting(true)
      try {
        await deleteAutoGeneratedConferenceById(conference.id)
        queryClient.invalidateQueries({ queryKey: ['auto-conferences'] })
        router.refresh()
      } catch (error) {
        console.error("Failed to delete auto-generated conference:", error)
      } finally {
        setIsDeleting(false)
      }
    }
  }

  const handleCopy = async () => {
    const url = `${window.location.origin}/auto-conferences/${conference.slug}`
    try {
      await navigator.clipboard.writeText(url)
      alert("Auto-generated conference link copied to clipboard!")
    } catch (error) {
      console.error("Failed to copy:", error)
    }
  }

  const handleShare = async () => {
    const url = `${window.location.origin}/auto-conferences/${conference.slug}`
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: conference.title,
          url: url,
        })
      } catch (error) {
        console.error("Error sharing:", error)
      }
    } else {
      handleCopy()
    }
  }

  return (
    <ActionMenu>
      <DropdownMenuItem asChild>
        <Link href={`/auto-conferences/${conference.slug}`}>
          <Eye className="mr-2 h-4 w-4" />
          View
        </Link>
      </DropdownMenuItem>
      <DropdownMenuItem asChild>
        <Link href={`/auto-conferences/${conference.id}/edit`}>
          <Edit className="mr-2 h-4 w-4" />
          Edit
        </Link>
      </DropdownMenuItem>
      <DropdownMenuItem onClick={handleCopy}>
        <Copy className="mr-2 h-4 w-4" />
        Copy Link
      </DropdownMenuItem>
      <DropdownMenuItem onClick={handleShare}>
        <Share2 className="mr-2 h-4 w-4" />
        Share
      </DropdownMenuItem>
      <DropdownMenuItem 
        onClick={handleDelete}
        disabled={isDeleting}
        className="text-red-600 focus:text-red-600"
      >
        <Trash2 className="mr-2 h-4 w-4" />
        {isDeleting ? "Deleting..." : "Delete"}
      </DropdownMenuItem>
    </ActionMenu>
  )
}