"use client"

import { DataTable } from "@/components/ui/data-table"
import { useQuery } from "@tanstack/react-query"
import { getAutoGeneratedConferences } from "../../actions"
import { columns } from "./columns"

export function AutoConferencesDataTable() {
  const { 
    data: conferencesData, 
    isLoading, 
    error 
  } = useQuery({
    queryKey: ['auto-conferences'],
    queryFn: getAutoGeneratedConferences,
  })

  if (isLoading) {
    return <div>Loading auto-generated conferences...</div>
  }

  if (error) {
    return <div>Error loading auto-generated conferences: {error.message}</div>
  }

  const conferences = conferencesData?.docs || []

  return (
    <DataTable
      columns={columns}
      data={conferences}
      searchKey="title"
      searchPlaceholder="Search auto-generated conferences..."
    />
  )
}